markdown: kramdown
highlighter: pygments
relative_permalinks: false
permalink: /news/:year/:month/:day/:title/
excerpt_separator: ""

gauges_id:
google_analytics_id:

repository: https://github.com/thilinah/icehrmblog
help_url: https://github.com/thilinah/icehrmblog

collections:
  docs:
    output: true
